#!/usr/bin/python

import spidev
import time
import os
import math
from datetime import datetime
ref_volt = 3.311

spi = spidev.SpiDev()
spi.open(0,0)

def ReadChannel(channel):
    adc = spi.xfer2([1,(8+channel) << 4,0])
    data = ((adc[1]&3)<<8) +adc[2]
    return data

def ConvertVolts(data,places):
    volts = (data*ref_volt)/float(1023)
    volts = round(volts,places)
    return volts

    
rms_ampno = 0
rms_amp = 0
channel0 = 0
channel1 = 1
count = 0
sleepdelay = 1
v = [0]
f = open('ProbeToPlot.csv', 'w')
g = open('ProbeToPlot3.csv', 'w')
alpha = 0.5569
y = [0]
    
    
NUMBER_OF_SAMPLES = 512

start_time = datetime.now()
    
for n in range (1, NUMBER_OF_SAMPLES):

    
    i = ReadChannel(channel0)
    j = ReadChannel(channel1)
    i = i - j
    v.append(ConvertVolts(i, 9))
    rms_ampno+=v[n]*v[n]    
    #stoptime = datetime.now()

rms_ampno=math.sqrt(rms_ampno/(NUMBER_OF_SAMPLES-1))
rms_ampno=rms_ampno/33*2000
stoptime = datetime.now()

print("{}A".format(rms_ampno))

f.write("{},".format(v))    
f.close()

print("Probe time : {} milliseconds ".format((stoptime -start_time).microseconds/1000))

for n in range (1, NUMBER_OF_SAMPLES):

    y.append(alpha*v[n]+(1-alpha)*y[n-1])
    rms_amp+=y[n]*y[n]

rms_amp=math.sqrt(rms_amp/(NUMBER_OF_SAMPLES-1))
rms_amp=rms_amp/33*2000

print("{}A".format(rms_amp))

g.write("{},".format(y))
g.close()
        


     








